env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 12
overrides:
  # override for jest
  - files:
      - "**/*.test.js"
    env:
      jest: true
rules: {}
